#Se déclenche quand on push sur n'importe quelle branche
name : documentation_workflow

on:
  push:
    branches:
      - 'master'

jobs:
  deplacer:
    runs-on: ubuntu-latest
    steps:
      #On se place dans le dépôt...
      - name: Checkout
        uses: actions/checkout@v4
      #Suite des actions...
      - name: mise a jour
        uses: actions/setup-java@v4
        with :
          java-version : 17
          distribution: 'oracle'
      - name: générer le site
        run : mvn javadoc::javadoc
      - name: publié le contenu sur la branche gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          publish_dir :  ./target/reports/apidocs/

