name : release.yml

on:
  push:
    tags:
      - '*'

permissions :
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      #On se place dans le dépôt...
      - name: Checkout
        uses: actions/checkout@v4
      #Suite des actions...
      - name: mise a jour
        uses: actions/setup-java@v4
        with :
          java-version : 17
          distribution: 'oracle'
      - name: changement de version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }} -DgenerateBackupPoms=false
      - name: creation de l'executable
        run: mvn package
      - name: creation d'une release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.ref_name }}